apiVersion: v1
kind: Service
metadata:
  name: everipixel-ui
  namespace: everipixel
  labels:
    app: evtd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: everipixel-ui
